export const viewMeta = {
  overview: {
    title: '总览',
    description: '桌面服务总览、连接状态和当前会话。',
  },
  pairing: {
    title: '连接授权',
    description: '管理手机接入策略、待审批请求和配对密码。',
  },
  control: {
    title: '桌面控制',
    description: '调试截图、鼠标、键盘与桌面输入链路。',
  },
  logs: {
    title: '日志事件',
    description: '查看桌面服务事件流、进程输出和最近错误。',
  },
};

export function createDom() {
  return {
    hostInput: document.querySelector('#hostInput'),
    portInput: document.querySelector('#portInput'),
    tokenInput: document.querySelector('#tokenInput'),
    pairPasswordInput: document.querySelector('#pairPasswordInput'),
    autoApproveInput: document.querySelector('#autoApproveInput'),
    serviceStatus: document.querySelector('#serviceStatus'),
    endpointText: document.querySelector('#endpointText'),
    lastExitText: document.querySelector('#lastExitText'),
    healthOutput: document.querySelector('#healthOutput'),
    pairingOutput: document.querySelector('#pairingOutput'),
    sessionOutput: document.querySelector('#sessionOutput'),
    actionOutput: document.querySelector('#actionOutput'),
    screenshotImage: document.querySelector('#screenshotImage'),
    screenshotMeta: document.querySelector('#screenshotMeta'),
    eventsList: document.querySelector('#eventsList'),
    pairRequestsList: document.querySelector('#pairRequestsList'),
    logsList: document.querySelector('#logsList'),
    pairingModal: document.querySelector('#pairingModal'),
    pairingModalBody: document.querySelector('#pairingModalBody'),
    pairingModalDismiss: document.querySelector('#pairingModalDismiss'),
    pairingModalApprove: document.querySelector('#pairingModalApprove'),
    pairingModalReject: document.querySelector('#pairingModalReject'),
    moveXInput: document.querySelector('#moveXInput'),
    moveYInput: document.querySelector('#moveYInput'),
    typeInput: document.querySelector('#typeInput'),
    keyInput: document.querySelector('#keyInput'),
    pageTitle: document.querySelector('#pageTitle'),
    pageDescription: document.querySelector('#pageDescription'),
    hostPill: document.querySelector('#hostPill'),
    portPill: document.querySelector('#portPill'),
    summaryEndpoint: document.querySelector('#summaryEndpoint'),
    summaryAuth: document.querySelector('#summaryAuth'),
    summaryMode: document.querySelector('#summaryMode'),
    startButton: document.querySelector('#startButton'),
    stopButton: document.querySelector('#stopButton'),
    healthButton: document.querySelector('#healthButton'),
    savePairingButton: document.querySelector('#savePairingButton'),
    pairStateButton: document.querySelector('#pairStateButton'),
    openSessionButton: document.querySelector('#openSessionButton'),
    heartbeatButton: document.querySelector('#heartbeatButton'),
    closeSessionButton: document.querySelector('#closeSessionButton'),
    screenshotButton: document.querySelector('#screenshotButton'),
    moveButton: document.querySelector('#moveButton'),
    clickButton: document.querySelector('#clickButton'),
    typeButton: document.querySelector('#typeButton'),
    keyButton: document.querySelector('#keyButton'),
    eventsButton: document.querySelector('#eventsButton'),
    openProjectButton: document.querySelector('#openProjectButton'),
    navItems: Array.from(document.querySelectorAll('.nav-item')),
    views: Array.from(document.querySelectorAll('.view-stack')),
  };
}
